FY-192/fix: build_check.yaml

diff --git a/.github/workflows/build_check.yaml b/.github/workflows/build_check.yaml
--- a/.github/workflows/build_check.yaml
+++ b/.github/workflows/build_check.yaml
@@ -13,23 +13,24 @@ jobs:
         strategy:
             matrix:
                 node-version: [16.x, 18.x, 20.x]
-    steps:
-    - uses: actions/checkout@v2
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v2
-      with:
-        node-version: ${{ matrix.node-version }}
-    - name: Install dependencies
-      run: npm i
-    - name: Run build
-      run: npm run build
-    - name: Check for build success
-      run: |
-        if [ $? -ne 0 ]; then
-          echo "Build failed with error code $?"
-          exit 1
-        fi
-    - name: Execute script forEach file
-      run: |
-        chmod +x ./scripts/execJsFile.sh
-        ./scripts/execJsFile.sh
+
+        steps:
+            - uses: actions/checkout@v2
+            - name: Use Node.js ${{ matrix.node-version }}
+              uses: actions/setup-node@v2
+              with:
+                  node-version: ${{ matrix.node-version }}
+            - name: Install dependencies
+              run: npm i
+            - name: Run build
+              run: npm run build
+            - name: Check for build success
+              run: |
+                  if [ $? -ne 0 ]; then
+                    echo "Build failed with error code $?"
+                    exit 1
+                  fi
+            - name: Execute script forEach file
+              run: |
+                  chmod +x ./scripts/execJsFile.sh
+                  ./scripts/execJsFile.sh
